
module.exports = {
  CMD_ONLINE: 0,
  CMD_OPEN: 1,
  CMD_SWIPE_UP: 2,
  CMD_SWIPE_RIGHT: 3,
  CMD_SWIPE_DOWN: 4,
  CMD_SWIPE_LEFT: 5,
  CMD_DOUBLE_CLICK: 6,
  CMD_BACK: 7,

  CMD_MAIN_LIVE: 8,
  CMD_LIVE_INPUT_COMMENT: 9,
  CMD_LIVE_SEND_COMMENT: 10,

  CMD_MAIN_SEARCH: 11,
  CMD_SEARCH_INPUT: 12,
  CMD_SEARCH_RESULT_AVATAR: 13,

  CMD_MINE_AVATAR: 14,

  
}